# Generated by Django 2.2 on 2019-11-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uo',
            name='niveauo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='uo',
            name='typeuo',
            field=models.CharField(choices=[('UNIT', 'UNIT'), ('PVAL', 'PVAL')], default=0, max_length=20),
        ),
    ]
