# Generated by Django 2.2 on 2020-04-21 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avancement',
            name='uo',
        ),
        migrations.RemoveField(
            model_name='pointage',
            name='uo',
        ),
        migrations.AlterField(
            model_name='avancement',
            name='semaine',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 21, 11, 57, 38, 711000, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='semaine',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 21, 11, 57, 38, 710000, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 21, 11, 57, 38, 709000, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 21, 11, 57, 38, 709000, tzinfo=utc), null=True),
        ),
    ]
