# Generated by Django 2.2 on 2020-01-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uo',
            name='jalaonD',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='uo',
            name='jalaonF',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='uo',
            name='ju',
            field=models.CharField(default='', max_length=20),
        ),
    ]
