# Generated by Django 2.2 on 2020-03-06 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0002_auto_20200306_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedecadrage',
            name='reponseRSA',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='uo',
            name='DateDebutUO',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 6, 7, 35, 4, 117099, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uo',
            name='DateLivraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 6, 7, 35, 4, 117099, tzinfo=utc)),
        ),
    ]
