# Generated by Django 2.2 on 2020-01-20 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0002_auto_20200117_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnesdentree', models.CharField(default='', max_length=600)),
                ('activiteAttendue', models.CharField(default='', max_length=600)),
                ('pourcentagedactivite', models.FloatField()),
                ('Conditionsdereussite', models.CharField(default='', max_length=600)),
                ('Datedonnéesdentrees', models.DateTimeField(blank=True, default='')),
                ('DatedeDemarragedActivite', models.DateTimeField(blank=True, default='')),
                ('LivrableAttendu', models.CharField(default='', max_length=600)),
                ('DatedeReceptionAttenduduLivrable', models.DateTimeField(blank=True, default='')),
                ('CommentairesSurAttendu', models.CharField(default='', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='NotedeCadrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponseRSA', models.CharField(default='', max_length=600)),
                ('activites', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='uos.Activites')),
                ('uo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='uos.Uo')),
            ],
        ),
    ]
