# Generated by Django 2.2 on 2019-11-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0003_etatuo_fonction_plateforme_projet_statutuo'),
    ]

    operations = [
        migrations.AddField(
            model_name='uo',
            name='etatuo',
            field=models.CharField(choices=[('alert/retard', 'alert/retard'), ('vivier', 'vivier'), ('cadré', 'cadré'), ('palnifié', 'palnifié'), ('abondonnée', 'abondonnée'), ('en cours', 'en cours'), ('terminée et livrée', 'terminée et livrée'), ('terminée et acceptée', 'terminée et acceptée'), ('refusée', 'refusée')], default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='uo',
            name='fonction',
            field=models.CharField(choices=[('LSS', 'LSS'), ('AEB', 'AEB')], default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='uo',
            name='plateforme',
            field=models.CharField(choices=[('CMFB', 'CMFB'), ('CMF1', 'CMF1')], default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='uo',
            name='projet',
            field=models.CharField(choices=[('BJA', 'BJA'), ('HJB', 'HJB'), ('JFC', 'JFC')], default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='uo',
            name='statutuo',
            field=models.CharField(choices=[('vivier', 'vivier'), ('livrée', 'livrée')], default=0, max_length=20),
        ),
    ]
