# Generated by Django 2.2 on 2020-01-20 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0003_activites_notedecadrage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notedecadrage',
            name='activites',
        ),
        migrations.AddField(
            model_name='activites',
            name='notedeCadrage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='uos.NotedeCadrage'),
        ),
    ]
