# Generated by Django 2.2 on 2020-04-21 12:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0003_auto_20200421_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancement',
            name='uo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='uos.Uo'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='uo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='uos.Uo'),
        ),
        migrations.AlterField(
            model_name='avancement',
            name='semaine',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 21, 12, 0, 44, 924000, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='semaine',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 21, 12, 0, 44, 924000, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 21, 12, 0, 44, 922000, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 21, 12, 0, 44, 923000, tzinfo=utc), null=True),
        ),
    ]
