# Generated by Django 2.2.4 on 2020-04-01 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0004_auto_20200401_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='semaine',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 1, 17, 37, 4, 804038, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 1, 17, 37, 4, 804038, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 1, 17, 37, 4, 804038, tzinfo=utc), null=True),
        ),
    ]
