# Generated by Django 2.2 on 2019-11-27 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0004_auto_20191122_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='UET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('fonctions', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='uos.fonction')),
            ],
        ),
    ]
