# Generated by Django 2.2 on 2020-04-21 12:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0004_auto_20200421_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancement',
            name='semaine',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 21, 12, 19, 2, 983000, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='semaine',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 21, 12, 19, 2, 982000, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 21, 12, 19, 2, 981000, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 21, 12, 19, 2, 981000, tzinfo=utc), null=True),
        ),
    ]
