# Generated by Django 2.2.3 on 2020-03-10 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0005_auto_20200310_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='semaine',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 10, 13, 28, 24, 195839, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 10, 13, 28, 24, 197406, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 10, 13, 28, 24, 197441, tzinfo=utc), null=True),
        ),
    ]
