# Generated by Django 2.2 on 2020-04-21 13:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0005_auto_20200421_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancement',
            name='semaine',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 21, 13, 19, 49, 183000, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='semaine',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 21, 13, 19, 49, 182000, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 21, 13, 19, 49, 181000, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 21, 13, 19, 49, 181000, tzinfo=utc), null=True),
        ),
    ]
