# Generated by Django 2.2 on 2020-01-21 10:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0005_auto_20200121_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='uo',
            name='DateDebutUO',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 21, 10, 1, 2, 76090, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='uo',
            name='DateLivraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 21, 10, 1, 2, 76090, tzinfo=utc)),
        ),
    ]
