# Generated by Django 2.2 on 2019-11-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0005_uet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='plateforme',
        ),
        migrations.RemoveField(
            model_name='uo',
            name='plateforme',
        ),
        migrations.AlterField(
            model_name='uo',
            name='projet',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
