# Generated by Django 2.2 on 2020-01-21 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0006_auto_20200121_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='uo',
            name='piloteUo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='uo',
            name='DateDebutUO',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 21, 10, 11, 1, 270090, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uo',
            name='DateLivraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 21, 10, 11, 1, 270090, tzinfo=utc)),
        ),
    ]
