# Generated by Django 2.2 on 2020-04-22 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0006_auto_20200421_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancement',
            name='semaine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='semaine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 22, 8, 53, 52, 377000, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 22, 8, 53, 52, 377000, tzinfo=utc), null=True),
        ),
    ]
