# Generated by Django 2.2 on 2019-11-27 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0006_auto_20191127_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='plateforme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('Projets', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='uos.projet')),
            ],
        ),
    ]
