# Generated by Django 2.2 on 2020-04-22 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0007_auto_20200422_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 22, 9, 53, 24, 576000, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 22, 9, 53, 24, 576000, tzinfo=utc), null=True),
        ),
    ]
