# Generated by Django 2.2 on 2019-11-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0007_plateforme'),
    ]

    operations = [
        migrations.AddField(
            model_name='uo',
            name='UET',
            field=models.CharField(choices=[('uet1', 'uet1'), ('uet2', 'uet2')], default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='uo',
            name='plateforme',
            field=models.CharField(choices=[('palatforme1', 'palatforme1'), ('plateforme2', 'plateforme2')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='uo',
            name='projet',
            field=models.CharField(choices=[('BJA', 'BJA'), ('proj1', 'proj1')], default=0, max_length=20),
        ),
    ]
