# Generated by Django 2.2.3 on 2020-01-22 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0007_auto_20200121_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uo',
            name='DateDebutUO',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 22, 13, 13, 20, 928890, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uo',
            name='DateLivraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 22, 13, 13, 20, 928915, tzinfo=utc)),
        ),
    ]
