# Generated by Django 2.2 on 2019-11-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0008_auto_20191127_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uo',
            name='plateforme',
            field=models.CharField(choices=[('palatforme1', 'palatforme1'), ('plateforme2', 'plateforme2'), ('plat4', 'plat4')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='uo',
            name='projet',
            field=models.CharField(choices=[('BJA', 'BJA'), ('proj1', 'proj1'), ('projet plat4', 'projet plat4')], default=0, max_length=20),
        ),
    ]
