# Generated by Django 2.2 on 2020-04-22 16:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0008_auto_20200422_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedecadrage',
            name='reponseRSA',
            field=models.CharField(blank=True, default='', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 22, 16, 3, 27, 490000, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 22, 16, 3, 27, 490000, tzinfo=utc), null=True),
        ),
    ]
