# Generated by Django 2.2 on 2020-04-23 06:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0009_auto_20200422_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='uo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='points', to='uos.Uo'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='points', to='profil.MyUsers'),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 23, 6, 52, 14, 662800, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 23, 6, 52, 14, 662800, tzinfo=utc), null=True),
        ),
    ]
