# Generated by Django 2.2 on 2020-04-23 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0011_auto_20200423_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uo',
            name='Pointage_total',
        ),
        migrations.RemoveField(
            model_name='uo',
            name='avancement_total',
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 23, 9, 29, 35, 672908, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 23, 9, 29, 35, 672908, tzinfo=utc), null=True),
        ),
    ]
