# Generated by Django 2.2 on 2020-04-23 09:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0013_auto_20200423_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 23, 9, 44, 51, 255109, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 23, 9, 44, 51, 255109, tzinfo=utc), null=True),
        ),
    ]
