# Generated by Django 2.2.3 on 2020-03-11 09:14

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0013_auto_20200311_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueuo',
            name='nbr_jour_uo',
            field=models.CharField(error_messages={'max_length': 'Le nombre de jour le ne doit pas depasser 5 chiffres'}, max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='semaine',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 11, 9, 14, 37, 321795, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 11, 9, 14, 37, 323415, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 11, 9, 14, 37, 323440, tzinfo=utc), null=True),
        ),
    ]
