# Generated by Django 2.2.3 on 2020-03-11 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0014_auto_20200311_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueuo',
            name='nbr_jour_uo',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='semaine',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 11, 9, 19, 0, 67894, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 11, 9, 19, 0, 69380, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 11, 9, 19, 0, 69401, tzinfo=utc), null=True),
        ),
    ]
