# Generated by Django 2.2 on 2020-04-23 09:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0014_auto_20200423_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancement',
            name='uo',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='avancement', to='uos.Uo'),
        ),
        migrations.AlterField(
            model_name='avancement',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='avancement', to='profil.Pilote'),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 23, 9, 49, 54, 548309, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 23, 9, 49, 54, 548309, tzinfo=utc), null=True),
        ),
    ]
