# Generated by Django 2.2.3 on 2020-03-09 10:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0015_auto_20200309_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uo',
            name='DateDebutUO',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 9, 10, 28, 41, 546172, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='DateLivraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 9, 10, 28, 41, 546196, tzinfo=utc), null=True),
        ),
    ]
