# Generated by Django 2.2.3 on 2020-03-11 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0015_auto_20200311_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointage',
            old_name='excutant',
            new_name='executant',
        ),
        migrations.RenameField(
            model_name='pointage',
            old_name='point_exceutant',
            new_name='point_executant',
        ),
        migrations.AlterField(
            model_name='pointage',
            name='semaine',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 11, 13, 59, 16, 951355, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 11, 13, 59, 16, 952855, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 11, 13, 59, 16, 952877, tzinfo=utc), null=True),
        ),
    ]
