# Generated by Django 2.2 on 2020-04-23 10:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0016_auto_20200423_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancement',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='avancement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 23, 10, 8, 25, 201311, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 23, 10, 8, 25, 201311, tzinfo=utc), null=True),
        ),
    ]
