# Generated by Django 2.2.3 on 2020-03-11 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0016_auto_20200311_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uo',
            old_name='nivea_uo',
            new_name='niveau_uo',
        ),
        migrations.AlterField(
            model_name='pointage',
            name='semaine',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 11, 15, 50, 54, 704748, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_debut_uo',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 11, 15, 50, 54, 706343, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='date_livraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 11, 15, 50, 54, 706367, tzinfo=utc), null=True),
        ),
    ]
