# Generated by Django 2.2.3 on 2020-03-09 13:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uos', '0025_auto_20200309_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activites',
            name='notedeCadrage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ref_cadrage', to='uos.NotedeCadrage'),
        ),
        migrations.AlterField(
            model_name='uo',
            name='DateDebutUO',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 9, 13, 25, 34, 13337, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='uo',
            name='DateLivraison',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 9, 13, 25, 34, 13363, tzinfo=utc), null=True),
        ),
    ]
