# Generated by Django 2.2.4 on 2020-04-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
