# Generated by Django 2.2.4 on 2020-04-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_auto_20200403_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
