# Generated by Django 2.2.3 on 2019-10-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_auto_20191015_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='poste',
            field=models.CharField(max_length=150),
        ),
    ]
