# Generated by Django 2.2 on 2020-03-06 10:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import profil.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('profil', '0002_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.PositiveIntegerField(blank=True, max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=profil.models.upload_location)),
                ('responsableUET', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.Client')),
            ],
            options={
                'verbose_name': 'Client',
            },
        ),
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=profil.models.upload_location)),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profil.NewPostName')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.Role')),
            ],
            options={
                'verbose_name': 'MyUser',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='liv',
            name='executant',
        ),
        migrations.RemoveField(
            model_name='liv',
            name='rt_liv',
        ),
        migrations.RemoveField(
            model_name='liv',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='ChefdeProjet',
            fields=[
                ('myusers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profil.MyUsers')),
            ],
            options={
                'verbose_name': 'Chef de projet',
            },
            bases=('profil.myusers',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Executant',
            fields=[
                ('myusers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profil.MyUsers')),
            ],
            options={
                'verbose_name': 'Executant',
            },
            bases=('profil.myusers',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pilote',
            fields=[
                ('myusers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profil.MyUsers')),
            ],
            options={
                'verbose_name': "Pilote d'activité",
            },
            bases=('profil.myusers',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RespSOP',
            fields=[
                ('myusers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profil.MyUsers')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.RespSOP')),
            ],
            options={
                'verbose_name': "SOP / Responsable d'activitée",
            },
            bases=('profil.myusers',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RespTechnique',
            fields=[
                ('myusers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profil.MyUsers')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.ChefdeProjet')),
            ],
            options={
                'verbose_name': 'RT',
            },
            bases=('profil.myusers',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='ChValid',
        ),
        migrations.DeleteModel(
            name='Liv',
        ),
        migrations.DeleteModel(
            name='Rt',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='pilote',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.RespTechnique'),
        ),
        migrations.AddField(
            model_name='executant',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.Pilote'),
        ),
        migrations.AddField(
            model_name='chefdeprojet',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.RespSOP'),
        ),
    ]
