# Generated by Django 2.2.3 on 2019-10-16 12:01

from django.db import migrations, models
import profil.models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0009_auto_20191016_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=profil.models.upload_location),
        ),
    ]
