# Generated by Django 2.2.3 on 2019-10-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0012_auto_20191017_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
