# Generated by Django 2.2.3 on 2019-10-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0013_remove_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('rt', 'RT'), ('liv', 'LIV')]},
        ),
    ]
