# Generated by Django 2.2.3 on 2019-10-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0014_auto_20191017_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('rt', 'RT'), ('liv', 'LIV ')], default='liv', max_length=9),
        ),
    ]
