# Generated by Django 2.2.3 on 2019-10-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0015_auto_20191017_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('RT', 'RT'), ('LIV', 'LIV ')], default='liv', max_length=9),
        ),
    ]
