# Generated by Django 2.2.3 on 2019-10-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0016_auto_20191017_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('rt', 'RT'), ('liv', 'LIV ')], default='liv', max_length=9),
        ),
    ]
