# Generated by Django 2.2.3 on 2019-10-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0017_auto_20191017_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.CharField(choices=[('activate', 'actif'), ('desactivate', 'desactive ')], default='activate', max_length=15),
        ),
    ]
