# Generated by Django 2.2.3 on 2019-10-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0018_userprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.CharField(blank=True, choices=[('activate', 'actif'), ('desactivate', 'desactive ')], default='activate', max_length=15, null=True),
        ),
    ]
