# Generated by Django 2.2.3 on 2019-10-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0019_auto_20191025_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='poste',
            field=models.CharField(choices=[('blank', ' '), ('ch.MIL', 'CH.MIL'), ('ch.HIL', 'CH.HIL '), ('ch.IS', 'CH.IS '), ('liv', "Pilote d'activité"), ('rt', 'RT '), ('pom', 'PMO'), ('rsop', 'RSOP')], default='blank', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('rt', 'RT'), ('liv', 'LIV'), ('ch.Valid', 'CH.VALID ')], default='ch.Valid', max_length=9),
        ),
    ]
