# Generated by Django 2.2.3 on 2019-10-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0020_auto_20191030_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='poste',
            field=models.CharField(choices=[('ch.MIL', 'CH.MIL'), ('ch.HIL', 'CH.HIL '), ('ch.IS', 'CH.IS '), ('liv', 'LIV'), ('rt', 'RT '), ('pmo', 'PMO'), ('rsop', 'RSOP')], default='ch.MIL', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('rt', 'RT'), ('pilote_activite', "PILOTE D'ACTIVITÉ"), ('charge_execution', 'CH.EXECUTION ')], default='ch.Valid', max_length=9),
        ),
    ]
