# Generated by Django 2.2.3 on 2019-11-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0024_remove_chvalid_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chvalid',
            name='relation',
            field=models.ManyToManyField(to='profil.Liv'),
        ),
    ]
