# Generated by Django 2.2.3 on 2019-11-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0025_chvalid_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chvalid',
            old_name='relation',
            new_name='superieur',
        ),
    ]
