# Generated by Django 2.2.3 on 2019-11-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0027_remove_chvalid_superieur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liv',
            name='equipe',
        ),
        migrations.AddField(
            model_name='chvalid',
            name='superieur',
            field=models.ManyToManyField(to='profil.Liv'),
        ),
    ]
