# Generated by Django 2.2.3 on 2019-11-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0029_liv_executant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chvalid',
            name='superieur',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='poste',
            field=models.CharField(choices=[('ch.MIL', 'CH.MIL'), ('ch.HIL', 'CH.HIL'), ('ch.IS', 'CH.IS'), ('liv', 'LIV'), ('rt', 'RT'), ('pmo', 'PMO'), ('rsop', 'RSOP')], max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('rt', 'RT'), ('pilote_activite', "PILOTE D'ACTIVITÉ"), ('charge_execution', 'CH.EXECUTION')], default='charge_execution', max_length=20),
        ),
    ]
