# Generated by Django 2.2.3 on 2019-11-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0030_auto_20191115_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='chvalid',
            name='superieur',
            field=models.ManyToManyField(to='profil.Liv'),
        ),
    ]
