# Generated by Django 2.2.3 on 2019-11-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0031_chvalid_superieur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liv',
            name='executant',
        ),
        migrations.RemoveField(
            model_name='liv',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChValid',
        ),
        migrations.DeleteModel(
            name='Liv',
        ),
    ]
