# Generated by Django 2.2.3 on 2019-11-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0033_chvalid_liv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chvalid',
            old_name='executant',
            new_name='referent',
        ),
    ]
