# Generated by Django 2.2.3 on 2019-11-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0034_auto_20191115_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liv',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChValid',
        ),
        migrations.DeleteModel(
            name='Liv',
        ),
    ]
