# Generated by Django 2.2.3 on 2019-11-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0036_chvalid_liv'),
    ]

    operations = [
        migrations.AddField(
            model_name='liv',
            name='executant',
            field=models.ManyToManyField(to='profil.ChValid'),
        ),
    ]
