# Generated by Django 2.2.3 on 2019-11-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0037_liv_executant'),
    ]

    operations = [
        migrations.AddField(
            model_name='chvalid',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profil.Liv'),
        ),
        migrations.AlterField(
            model_name='liv',
            name='executant',
            field=models.ManyToManyField(blank=True, to='profil.ChValid'),
        ),
    ]
