# Generated by Django 2.2.3 on 2019-11-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0039_auto_20191121_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liv',
            name='executant',
            field=models.ManyToManyField(blank=True, related_name='liv', to='profil.ChValid'),
        ),
    ]
