# Generated by Django 2.2.3 on 2019-11-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0040_auto_20191126_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liv',
            name='executant',
            field=models.ManyToManyField(blank=True, related_name='executant', to='profil.ChValid'),
        ),
    ]
