# Generated by Django 2.2.3 on 2019-11-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0041_auto_20191126_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liv',
            name='executant',
            field=models.ManyToManyField(blank=True, to='profil.ChValid'),
        ),
    ]
