# Generated by Django 2.2.3 on 2019-12-02 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0044_auto_20191128_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chvalid',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='profil.Liv'),
        ),
    ]
