# Generated by Django 2.2.3 on 2019-12-02 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0045_auto_20191202_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chvalid',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsp', to='profil.Liv'),
        ),
    ]
