# Generated by Django 2.2.3 on 2020-01-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0048_auto_20200106_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeDePoste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=150)),
            ],
        ),
    ]
