# Generated by Django 2.2.3 on 2020-01-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0049_listedeposte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListeDePoste',
        ),
    ]
