# Generated by Django 2.2.3 on 2020-01-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0051_listedeposte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listedeposte',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.UserProfile'),
        ),
    ]
