# Generated by Django 2.2.3 on 2020-01-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0052_auto_20200107_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listedeposte',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='listedeposte',
            name='user',
        ),
    ]
