# Generated by Django 2.2.3 on 2020-01-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0053_auto_20200107_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedeposte',
            name='poste',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
