# Generated by Django 2.2.3 on 2020-01-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0055_remove_listedeposte_poste'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomDePoste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_poste', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='listedeposte',
            name='liste_de_poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.NomDePoste'),
        ),
    ]
