# Generated by Django 2.2.3 on 2020-01-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0056_auto_20200107_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListeDePoste',
        ),
        migrations.DeleteModel(
            name='NomDePoste',
        ),
    ]
