# Generated by Django 2.2.3 on 2020-01-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0058_nomdeposte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomdeposte',
            name='user',
        ),
    ]
