# Generated by Django 2.2.3 on 2020-01-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0059_remove_nomdeposte_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomdeposte',
            name='nom_de_poste',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
