# Generated by Django 2.2.3 on 2020-01-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0061_auto_20200108_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='poste',
            field=models.CharField(max_length=150),
        ),
    ]
