# Generated by Django 2.2.3 on 2020-01-08 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0062_auto_20200108_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.NomDePoste'),
        ),
    ]
