# Generated by Django 2.2.3 on 2020-01-08 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0063_auto_20200108_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomdeposte',
            name='nom_de_poste',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.NomDePoste'),
        ),
    ]
