# Generated by Django 2.2.3 on 2020-01-10 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0065_auto_20200108_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPostName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(blank=True, error_messages={'unique': 'Existe deja'}, max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profil.NewPostName'),
        ),
        migrations.DeleteModel(
            name='NomDePoste',
        ),
    ]
