# Generated by Django 2.2.3 on 2020-01-20 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0066_auto_20200110_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpostname',
            name='post_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
