# Generated by Django 2.2.3 on 2020-01-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0070_auto_20200120_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpostname',
            name='post_name',
            field=models.CharField(blank=True, error_messages={'unique': 'Ce poste existe déja !'}, max_length=150, unique=True),
        ),
    ]
