# Generated by Django 2.2.3 on 2020-01-20 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0072_auto_20200120_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpostname',
            name='post_name',
            field=models.CharField(blank=True, default=django.utils.timezone.now, error_messages={'unique': 'Ce poste existe déja !'}, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
